### PR TITLE
Update Gradle 8 compatibility

### PR DESCRIPTION
**Pull request by gabe-robles**

### CODE REVIEW

**Comment by MyBlueford16** [comment]
@kphanipavan  any chance this can get merged in soon?

**Comment by kphanipavan** [comment]
Hi, 
Apoligies for delayed response. I am planning to convert this plugin into a package, which doesn't require maintaining platform specific compatibility. I will merge this if you require so.

image
Ref: https://docs.flutter.dev/packages-and-plugins/using-packages


@gabe-robles, please remove `.idea` folder, I will then merge it...

**Review by kphanipavan — CHANGES_REQUESTED** [review]
Remove .idea and all of its content

**Comment by gabe-robles** [comment]
Hi @kphanipavan I've removed the `.idea` folder and its contents from my pull request.

**Review by kphanipavan — APPROVED** [review]
Tq.

-Pvn

**Pull request merged**
